version: 2
jobs:
  build:
    machine:
      enabled: true
    steps:
      - checkout

      - run:
          name: Install cfn-create-or-update
          command: npm install -g cfn-create-or-update
      - run:
          name: Create stack and s3 bucket using CFT
          command: cfn-create-or-update --stack-name my-stack --template-body file://cloud.yml --region eu-west-1 --wait
