version: 2
jobs:
  build:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: KloudFormation Install
          command: curl -s https://install.kloudformation.hexlabs.io/kloudformation.sh -o kloudformation.sh
      - run:
          name: KloudFormation Run
          command: ./kloudformation.sh -stack-file stack/Stack.kt
      - run:
          name: Install cfn-create-or-update
          command: npm install -g cfn-create-or-update
      - run:
          name: Create stack and s3 bucket using CFT
          command: cfn-create-or-update --stack-name my-stack --template-body file://template.yml --region eu-west-1 --wait
